[package]
name = "tuplez"
version = "0.1.0"
authors = ["Daniel Diaz <diaz.carrete@facebook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
